package cn.datamining.dat.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, String> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UserId = new Property(0, String.class, "userId", true, "USER_ID");
        public final static Property UserName = new Property(1, String.class, "userName", false, "USER_NAME");
        public final static Property NickName = new Property(2, String.class, "nickName", false, "NICK_NAME");
        public final static Property AliasName = new Property(3, String.class, "aliasName", false, "ALIAS_NAME");
        public final static Property UserHead = new Property(4, String.class, "userHead", false, "USER_HEAD");
        public final static Property UserPhone = new Property(5, String.class, "userPhone", false, "USER_PHONE");
        public final static Property UserEmail = new Property(6, String.class, "userEmail", false, "USER_EMAIL");
        public final static Property Birthday = new Property(7, String.class, "birthday", false, "BIRTHDAY");
        public final static Property UserCompany = new Property(8, String.class, "userCompany", false, "USER_COMPANY");
        public final static Property UserPosition = new Property(9, String.class, "userPosition", false, "USER_POSITION");
        public final static Property Version = new Property(10, String.class, "version", false, "VERSION");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"USER_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: userId
                "\"USER_NAME\" TEXT," + // 1: userName
                "\"NICK_NAME\" TEXT," + // 2: nickName
                "\"ALIAS_NAME\" TEXT," + // 3: aliasName
                "\"USER_HEAD\" TEXT," + // 4: userHead
                "\"USER_PHONE\" TEXT," + // 5: userPhone
                "\"USER_EMAIL\" TEXT," + // 6: userEmail
                "\"BIRTHDAY\" TEXT," + // 7: birthday
                "\"USER_COMPANY\" TEXT," + // 8: userCompany
                "\"USER_POSITION\" TEXT," + // 9: userPosition
                "\"VERSION\" TEXT);"); // 10: version
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(1, userId);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(2, userName);
        }
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(3, nickName);
        }
 
        String aliasName = entity.getAliasName();
        if (aliasName != null) {
            stmt.bindString(4, aliasName);
        }
 
        String userHead = entity.getUserHead();
        if (userHead != null) {
            stmt.bindString(5, userHead);
        }
 
        String userPhone = entity.getUserPhone();
        if (userPhone != null) {
            stmt.bindString(6, userPhone);
        }
 
        String userEmail = entity.getUserEmail();
        if (userEmail != null) {
            stmt.bindString(7, userEmail);
        }
 
        String birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindString(8, birthday);
        }
 
        String userCompany = entity.getUserCompany();
        if (userCompany != null) {
            stmt.bindString(9, userCompany);
        }
 
        String userPosition = entity.getUserPosition();
        if (userPosition != null) {
            stmt.bindString(10, userPosition);
        }
 
        String version = entity.getVersion();
        if (version != null) {
            stmt.bindString(11, version);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(1, userId);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(2, userName);
        }
 
        String nickName = entity.getNickName();
        if (nickName != null) {
            stmt.bindString(3, nickName);
        }
 
        String aliasName = entity.getAliasName();
        if (aliasName != null) {
            stmt.bindString(4, aliasName);
        }
 
        String userHead = entity.getUserHead();
        if (userHead != null) {
            stmt.bindString(5, userHead);
        }
 
        String userPhone = entity.getUserPhone();
        if (userPhone != null) {
            stmt.bindString(6, userPhone);
        }
 
        String userEmail = entity.getUserEmail();
        if (userEmail != null) {
            stmt.bindString(7, userEmail);
        }
 
        String birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindString(8, birthday);
        }
 
        String userCompany = entity.getUserCompany();
        if (userCompany != null) {
            stmt.bindString(9, userCompany);
        }
 
        String userPosition = entity.getUserPosition();
        if (userPosition != null) {
            stmt.bindString(10, userPosition);
        }
 
        String version = entity.getVersion();
        if (version != null) {
            stmt.bindString(11, version);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // userId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // nickName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // aliasName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // userHead
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // userPhone
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // userEmail
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // birthday
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // userCompany
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // userPosition
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // version
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setUserId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUserName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNickName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAliasName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUserHead(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUserPhone(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setUserEmail(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBirthday(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUserCompany(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setUserPosition(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setVersion(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    @Override
    protected final String updateKeyAfterInsert(User entity, long rowId) {
        return entity.getUserId();
    }
    
    @Override
    public String getKey(User entity) {
        if(entity != null) {
            return entity.getUserId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getUserId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
